### ISSUE TITLE
Adding Table of Content to Readme.md 

### ISSUE THREAD

**Issue by ng29** [Nexmo/nexmo-spring-boot-starter#7]
@lornajane  / @cr0wst 

The idea for Adding Table of Content to Readme.md to add additional enhancement and readability to the docs file.

I would like to work on this issue.

Cheers

**Comment by yallen011** [comment]
Hi @ng29, you may work in this. Please make it look similar to TOC shown in the [Vonage Server SDK](https://github.com/Vonage/vonage-java-sdk) README

**Comment by ng29** [comment]
Sure @yallen011 please assign me this isssue 👍

**Comment by ng29** [comment]
Hey, @yallen011 readme has been updated with TOC, please review the pull request for the same.

Cheers,
