### ISSUE TITLE
Convert Project from Kotlin to Java

### ISSUE THREAD

**Issue by yallen011** [Nexmo/nexmo-spring-boot-starter#8]
The project is currently written in Kotlin. It needs to be rewritten in Java.

**Comment by JaredEzz** [comment]
I would like to work on this.

**Comment by AugustasV** [comment]
But just. Why? It's like going backwords. Kotlin is greater than Java!

**Comment by akshitadixit** [comment]
@yallen011 please assign this to me :)

**Comment by yallen011** [comment]
This is great. Thank you @akshitadixit @AugustasV @JaredEzz for all being willing to work on this. We are deciding to take another approach and leave this repo in Kotlin and create another version of the Nexmo Spring Boot Starter in java. You can find the repo [here](https://github.com/Nexmo/vonage-spring-boot-starter-java/) If all 3 of you want to work on it, that is fine. Comment that you would like to work on this in the issue I have created [here](https://github.com/Nexmo/vonage-spring-boot-starter-java/issues/1), and I break the issue into subtasks so that you all can work on it.

**Comment by yallen011** [comment]
closing this issue as all conversions should be moved over to this issue

**Comment by yallen011** [comment]
closing this issue as all conversions should be moved over to this issue here

**Comment by yallen011** [comment]
@AugustasV @JaredEzz we have another issue that just opened up if one of you would like to grab it #10
